apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: alert-sample
spec:
  providerRef:
    name: slack-provider-sample
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
